### ISSUE TITLE
HBW-LC-Bl-4 wird in CCU2 nur als HMW-Generic angezeigt

### ISSUE THREAD

**Issue by grogo08** [ThorstenPferdekaemper/HBWired#8]
Hallo zusammen,

ich habe mich mal an den Device HBW-LC-BL-4 versucht. Den Quellcode habe ich in den Adruino geladen und ich sehe auch auf dem RS485-Bus die Kommandos vom Device.

Dann habe ich auf die CCU2 die XML Datei in das Verzeichnis /firmware/hs485types geladen und die Rechte der Datei auf chmod 755 wie bei den anderen Dateien gesetzt und dann die CCU2 neu gestartet.

Wenn ich dann auf "Gerät anlernen" im WebUI der CCU2 klicke, wird mir im Posteingang ein neues Device angezeigt. Dies hat auch die eingestellte Serienunner aber leider wird das Device als HMW-Generic angezeigt und ist nicht bedienbar.

Weiß jmd was ich falsch mache? Hab schon einiges ausprobiert, aber es klappt nicht. Muss man sonst noch irgendwo was eintragen, oder irgendwelche Dienste neu starten?

Hab auch schon andere Selbstbau-Devices an der Zentrale anmelden können, aber dieses klappt irgendwie nicht :(

Danke für eure Antworten.

**Comment by ThorstenPferdekaemper** [comment]
Hi,
hast Du das schon in FHEM ausprobiert? Die CCUs werden nur so am Rande unterstützt, da man da leider nicht sehen kann, was die Dinger wirklich treiben. 
Hast Du schon einmal versucht, die Zeile mit der Firmware Version im XML-File wegzulassen?
Gruß,
   Thorsten

**Comment by grogo08** [comment]
Hi Thorsten,
habe es noch nicht in FHEM versucht, habe auch leider keine FHEM Zentrale da.

Du hast reicht, bei der CCU2 kann man wirklich nicht sehen, ob das XML File richtig geladen wird.

Hab jetzt auch mal die Firmware gelöscht, aber leider ohne Erfolg.

**Comment by ThorstenPferdekaemper** [comment]
Hi,
nein, soweit ich weiß. ...aber wer weiß das schon, bei dem ganzen Closed-Source-Mist. 
Vielleicht kannst Du mal vergleichen, worin sich dieses XML von den bisher erfolgreichen unterscheidet. Vielleicht mag die CCU auch den Dateinamen nicht.
Gruß,
   Thorsten

**Comment by ThorstenPferdekaemper** [comment]
...ansonsten kann ich Dir nur empfehlen, einen entsprechenden Thread im FHEM-Forum (Homematic-Bereich) aufzumachen. Dort lesen wesentlich mehr mit als hier auf GitHub.
Gruß,
   Thorsten

**Comment by loetmeister** [comment]
Hallo,

habe die XML und/oder Sketch angepasst: https://github.com/loetmeister/HBWired/commit/bd72f6dc984ed3a820de34a036806e066bee7532

**Comment by loetmeister** [comment]
Hi,

denke das könnte man schließen? Denke das Problem wurde ja gelöst… :-)

**Comment by ThorstenPferdekaemper** [comment]
Ok, ich machs zu.
